### ISSUE TITLE
Extra length

### ISSUE THREAD

**Issue by MiniGod** [juliangruber/split-by-header#1]
I'm working with a protocol which looks like:

```
UInt32LE - length of xml data
UInt32LE - request id
String   - xml data
```

The total length of each request is therefore 4 bytes longer than what the `length` is saying.

Would you be anything against changing the api to: `split(type, additionalLength)`?
`additionalLength` could either be a number or a type (`UInt32LE` in this case).

**Comment by MiniGod** [comment]
Just realized that your implementation expects the `length` to "include it self".

From example: `splitter.write(new Buffer([3, 1, 1]));`
Length 3 total, but only 2 bytes of data.

In my case, an example would be:

``` javascript
var splitter = split('UInt32LE');
splitter.on('data', console.log);
// => <Buffer 05 09 05>>
splitter.write(new Buffer(
[   3, 0, 0, 0 // length = 3
,   9, 0, 0, 0 // request id = 9
,   5, 9, 5 // the data. 3 bytes.
]));
```

Do you see any simple way of supporting this?

**Comment by juliangruber** [comment]
I think I had the same problem and started writing [barse](https://github.com/juliangruber/barse), something more generic. The api to parse your protocal would be:

``` js
var parser = parse()
  .readUInt32LE('xml length')
  .readUInt32LE('request id')
  .string('xml data', 'xml length')
```
